import { getStore } from '@netlify/blobs';
import { createHash } from 'node:crypto';
import { apiHeaders, canAccessClinic, requireUser, sameOriginRequest } from './lib/session.mjs';

const headers=apiHeaders('GET,PUT,OPTIONS');const reply=(data,status=200)=>new Response(JSON.stringify(data),{status,headers});const store=getStore({name:'clinic-prescriptions',consistency:'strong'});const hash=value=>createHash('sha256').update(String(value)).digest('hex');const text=(value,max=500)=>String(value??'').trim().slice(0,max);
const validClinic=value=>/^clinic-([1-9]|1[0-5])$/.test(value||'');const validDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(value||'');const validPatient=value=>/^[a-zA-Z0-9._:-]{1,80}$/.test(value||'');
const cleanMedicine=value=>({template:['augmentin','metronidazole','prednisolone','other'].includes(value?.template)?value.template:'other',name:text(value?.name,100),strength:text(value?.strength,60),frequency:text(value?.frequency,100),duration:text(value?.duration,50),instructions:text(value?.instructions,500)});
const cleanPrescription=value=>({patient:{id:text(value?.patient?.id,80),name:text(value?.patient?.name,120),file:text(value?.patient?.file,40),phone:text(value?.patient?.phone,20)},diagnosis:text(value?.diagnosis,500),medicines:(Array.isArray(value?.medicines)?value.medicines:[]).slice(0,12).map(cleanMedicine).filter(item=>item.name),notes:text(value?.notes,500),medicalReview:Boolean(value?.medicalReview),status:value?.status==='issued'?'issued':'draft',issuedAt:text(value?.issuedAt,40)});
export default async request=>{if(request.method==='OPTIONS')return new Response(null,{status:204,headers});if(!['GET','PUT'].includes(request.method))return reply({error:'Method not allowed'},405);if(request.method==='PUT'&&!sameOriginRequest(request))return reply({error:'Invalid request origin'},403);const auth=await requireUser(request);if(!auth.ok)return reply({error:auth.error},auth.status);const url=new URL(request.url),patientId=url.searchParams.get('patientId')||'',date=url.searchParams.get('date')||'',clinicId=url.searchParams.get('clinic')||'';if(!validPatient(patientId)||!validDate(date)||!validClinic(clinicId))return reply({error:'Invalid prescription key'},400);if(!canAccessClinic(auth.user,clinicId))return reply({error:'Clinic access denied'},403);const key=`clinics/${clinicId}/days/${date}/patients/${hash(patientId)}`;if(request.method==='GET'){const record=await store.get(key,{type:'json',consistency:'strong'});return reply({ok:true,record:record||null})}const body=await request.json().catch(()=>null),prescription=cleanPrescription(body?.prescription);if(!prescription.diagnosis||!prescription.medicines.length||!prescription.medicalReview)return reply({error:'Prescription review is incomplete'},400);const existing=await store.get(key,{type:'json',consistency:'strong'});const record={patientId,clinicId,date,prescription,revision:Number(existing?.revision||0)+1,updatedAt:Date.now(),updatedBy:text(auth.user?.displayName||auth.user?.username,120)};await store.setJSON(key,record);return reply({ok:true,record})};
