'use strict';
const $=id=>document.getElementById(id);const params=new URLSearchParams(location.search);const patientId=params.get('patientId')||'',date=params.get('date')||'',clinic=params.get('clinic')||'clinic-1',view=params.get('view')||'clinic';let patient=null,record=null,selectedMedicines=[],editingMedicine=-1;
const NOTICE='DRAFT — NOT MEDICAL ADVICE — DOCUMENTATION-ONLY — AUTHORIZED CLINICIAN SIGN-OFF REQUIRED';
const CATEGORY_LABELS={antibiotic:'مضاد حيوي',analgesic:'مسكن',mouthwash:'مضمضة',legacy:'علاج محفوظ سابقًا'};
const CATALOG={
  antibiotic:[
    {id:'augmentin',label:'Amoxicillin / Clavulanate (Augmentin)',name:'Amoxicillin / Clavulanate (Augmentin)',strengths:['625 mg','1000 mg'],frequencies:['BID','TID'],durations:['3 أيام','5 أيام']},
    {id:'metronidazole',label:'Metronidazole',name:'Metronidazole',strengths:['500 mg'],frequencies:['BID','TID'],durations:['3 أيام','5 أيام']},
    {id:'custom-antibiotic',label:'مضاد آخر معتمد محليًا',name:''}
  ],
  analgesic:[{id:'custom-analgesic',label:'مسكن معتمد محليًا',name:''}],
  mouthwash:[{id:'custom-mouthwash',label:'مضمضة معتمدة محليًا',name:''}]
};
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const api=async(url,options={})=>{const response=await fetch(url,{credentials:'include',cache:'no-store',...options});const data=await response.json().catch(()=>({}));if(response.status===401){location.href=`./?returnTo=${encodeURIComponent(location.href)}`;throw new Error('انتهت الجلسة')}if(!response.ok){const error=new Error(data.error||'تعذر إكمال الطلب');error.status=response.status;throw error}return data};
const stateUrl=`/api/state?date=${encodeURIComponent(date)}&clinic=${encodeURIComponent(clinic)}`;
const normalizePhone=value=>String(value||'').replace(/\D/g,'').replace(/^00966/,'0').replace(/^966/,'0').replace(/^5(?=\d{8}$)/,'05');
function prescriptionUrl(extra={}){const query=new URLSearchParams({patientId,date,clinic,file:String(patient?.file||''),phone:normalizePhone(patient?.phone),nationalId:String(patient?.nationalId||''),...extra});return`/api/prescriptions?${query.toString()}`}
function setOptions(node,values=[]){node.innerHTML=(values||[]).map(value=>`<option value="${esc(value)}"></option>`).join('')}
function resetEditor(){editingMedicine=-1;$('medicineEditor').hidden=true;$('medicineCategory').value='';$('medicinePreset').innerHTML='<option value="">اختر النوع أولًا</option>';$('medicinePreset').disabled=true;['medicineName','medicineStrength','medicineDose','medicineFrequency','medicineDuration','medicineInstructions'].forEach(id=>$(id).value='');$('cancelMedicineEdit').hidden=true;$('addMedicineBtn').textContent='＋ إضافة إلى الوصفة'}
function showEditor(category,preset={}){$('medicineEditor').hidden=false;$('medicineEditorTitle').textContent=preset.label||CATEGORY_LABELS[category]||'تفاصيل العلاج';$('medicineName').value=preset.name||'';$('medicineStrength').value='';$('medicineDose').value='';$('medicineFrequency').value='';$('medicineDuration').value='';$('medicineInstructions').value=preset.instructions||'';setOptions($('strengthSuggestions'),preset.strengths);setOptions($('frequencySuggestions'),preset.frequencies);setOptions($('durationSuggestions'),preset.durations);$('medicineName').focus()}
function updatePresetList(){const category=$('medicineCategory').value,items=CATALOG[category]||[];$('medicinePreset').disabled=!category;$('medicinePreset').innerHTML=`<option value="">${category?'اختر العلاج':'اختر النوع أولًا'}</option>${items.map(item=>`<option value="${esc(item.id)}">${esc(item.label)}</option>`).join('')}`;$('medicineEditor').hidden=true}
function editorMedicine(){const category=$('medicineCategory').value;return{category,template:$('medicinePreset').value||'custom',name:$('medicineName').value.trim(),strength:$('medicineStrength').value.trim(),dose:$('medicineDose').value.trim(),frequency:$('medicineFrequency').value.trim(),duration:$('medicineDuration').value.trim(),instructions:$('medicineInstructions').value.trim()}}
function editorError(medicine){if(!medicine.category)return'اختر نوع العلاج.';if(!medicine.name)return'أدخل اسم العلاج.';if(!medicine.dose)return'أدخل الجرعة كما اعتمدها الطبيب.';if(!medicine.frequency)return'أدخل تكرار الاستخدام.';if(!medicine.duration)return'أدخل مدة الاستخدام.';return''}
function renderSelected(){const target=$('selectedMedicines');if(!selectedMedicines.length){target.innerHTML='<div class="empty-state">لم تتم إضافة علاج بعد.</div>';renderPreview();return}target.innerHTML=selectedMedicines.map((medicine,index)=>`<article class="selected-medicine"><span class="med-icon" aria-hidden="true">💊</span><div><strong>${esc(medicine.name)} ${esc(medicine.strength)}</strong><small>${esc(CATEGORY_LABELS[medicine.category]||CATEGORY_LABELS.legacy)} · ${esc(medicine.dose)} · ${esc(medicine.frequency)} · ${esc(medicine.duration)}</small>${medicine.instructions?`<small>${esc(medicine.instructions)}</small>`:''}</div><div class="selected-medicine-actions"><button type="button" data-edit-medicine="${index}">تعديل</button><button type="button" class="danger" data-remove-medicine="${index}">حذف</button></div></article>`).join('');renderPreview()}
function addOrUpdateMedicine(){const medicine=editorMedicine(),error=editorError(medicine);$('formError').textContent=error;if(error)return;if(editingMedicine>=0)selectedMedicines[editingMedicine]=medicine;else selectedMedicines.push(medicine);resetEditor();renderSelected()}
function editMedicine(index){const medicine=selectedMedicines[index];if(!medicine)return;editingMedicine=index;const supported=CATALOG[medicine.category]?medicine.category:'';$('medicineCategory').value=supported;$('medicinePreset').disabled=!supported;$('medicinePreset').innerHTML=supported?`<option value="custom">قالب محفوظ قابل للتعديل</option>`:'<option value="">وصفة سابقة — اختر النوع قبل الحفظ</option>';$('medicinePreset').value=supported?'custom':'';$('medicineEditor').hidden=false;$('medicineEditorTitle').textContent=`تعديل ${medicine.name}`;['Name','Strength','Dose','Frequency','Duration','Instructions'].forEach(field=>$(`medicine${field}`).value=medicine[field.toLowerCase()]||'');$('cancelMedicineEdit').hidden=false;$('addMedicineBtn').textContent='حفظ تعديل العلاج';$('medicineName').focus()}
function validate(){if(!$('diagnosis').value.trim())return'أدخل التشخيص أو سبب الوصفة.';if(!selectedMedicines.length)return'أضف علاجًا واحدًا على الأقل.';const incomplete=selectedMedicines.find(editorError);if(incomplete)return`راجع بيانات ${incomplete.name||'العلاج'}: ${editorError(incomplete)}`;if(!$('medicalReview').checked)return'أكد اكتمال المراجعة الطبية في النظام المعتمد.';if(!$('doctorConfirm').checked)return'يلزم تأكيد الطبيب المخوّل قبل إرسال الوصفة.';return''}
function payload(status='ready_for_admin'){return{patient:{id:patientId,name:patient?.name||'',file:patient?.file||'',phone:normalizePhone(patient?.phone),nationalId:patient?.nationalId||''},diagnosis:$('diagnosis').value.trim(),medicines:selectedMedicines.map(item=>({...item})),notes:$('notes').value.trim(),medicalReview:Boolean($('medicalReview').checked),doctorConfirmed:Boolean($('doctorConfirm').checked),notice:NOTICE,status,issuedAt:new Date().toISOString(),sourcePatientId:patientId,sourceDate:date}}
function renderPreview(data=payload(record?.status||'ready_for_admin')){const meds=data.medicines||[];$('printPatient').innerHTML=`<b>المريض:</b> ${esc(patient?.name||data.patient?.name||'—')} &nbsp; <b>رقم الملف:</b> ${esc(patient?.file||data.patient?.file||'—')} &nbsp; <b>الجوال:</b> ${esc(patient?.phone||data.patient?.phone||'—')}`;$('printDiagnosis').innerHTML=`<b>التشخيص:</b> ${esc(data.diagnosis||'—')}`;$('printMedicines').innerHTML=meds.map(m=>`<li><b>${esc(m.name)} ${esc(m.strength)}</b> — ${esc(m.dose)}، ${esc(m.frequency)}، ${esc(m.duration)}<br>${esc(m.instructions)}</li>`).join('');$('printNotes').innerHTML=data.notes?`<b>ملاحظات:</b> ${esc(data.notes)}`:'';$('issuedAt').textContent=new Date(data.issuedAt||Date.now()).toLocaleString('ar-SA')}
function restore(data){if(!data)return;$('diagnosis').value=data.diagnosis||'';$('notes').value=data.notes||'';$('medicalReview').checked=Boolean(data.medicalReview);$('doctorConfirm').checked=Boolean(data.doctorConfirmed||data.status==='issued'||data.status==='ready_for_admin'||data.status==='shared');selectedMedicines=(data.medicines||[]).map(medicine=>({category:medicine.category||(['augmentin','metronidazole'].includes(medicine.template)?'antibiotic':'legacy'),template:medicine.template||'custom',name:medicine.name||'',strength:medicine.strength||'',dose:medicine.dose||'حسب وصف الطبيب',frequency:medicine.frequency||'',duration:medicine.duration||'',instructions:medicine.instructions||''}));renderSelected();renderPreview(data)}
function historyEntries(){if(Array.isArray(record?.history)&&record.history.length)return record.history;return record?.prescription?[{at:record.updatedAt,status:record.status,prescription:record.prescription,by:record.updatedBy}]:[]}
function renderHistory(){const target=$('prescriptionHistory'),history=historyEntries().slice().reverse();if(!history.length){target.innerHTML='<div class="empty-state">لا توجد وصفات سابقة محفوظة.</div>';return}target.innerHTML=`<div class="history-list">${history.map((entry,index)=>`<article class="history-item"><div><strong>${new Date(Number(entry.at||Date.now())).toLocaleString('ar-SA')}</strong><small>${esc(entry.by||'مستخدم النظام')} · ${(entry.prescription?.medicines||[]).length} علاج</small><span class="history-status ${entry.status==='shared'?'shared':''}">${entry.status==='shared'?'تمت مشاركتها مع المريض':'معتمدة من الطبيب — لدى الإدارة'}</span></div><div class="history-actions"><button type="button" data-history-index="${history.length-1-index}">استعادة هذه النسخة</button></div></article>`).join('')}</div>`}
async function savePrescription(status='ready_for_admin'){const error=validate();$('formError').textContent=error;if(error)throw new Error(error);const data=await api(prescriptionUrl(),{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({prescription:payload(status),expectedRevision:Number(record?.revision||0)})});record=data.record;renderHistory();renderPreview(record.prescription);return data.record}
function whatsappText(data){const list=(data.medicines||[]).map((m,i)=>`${i+1}. ${m.name}${m.strength?` — ${m.strength}`:''}\nالجرعة: ${m.dose}\nالتكرار: ${m.frequency}\nالمدة: ${m.duration}${m.instructions?`\nالتعليمات: ${m.instructions}`:''}`).join('\n\n');return`مرفق لكم الوصفة الطبية المعتمدة من الطبيب\nالمريض: ${patient.name}\nرقم الملف: ${patient.file}\n\n${list}\n\nتُستخدم الأدوية حسب تعليمات الطبيب المدوّنة فقط.`}
async function markSharedAfterSuccess(){if(view!=='admin')return;await savePrescription('shared')}
async function sharePrescription(){const popup=!navigator.share?window.open('about:blank','_blank'):null;try{const saved=await savePrescription('ready_for_admin'),text=whatsappText(saved.prescription),phone=String(patient.phone||'').replace(/\D/g,'').replace(/^0/,'966');if(navigator.share){try{await navigator.share({title:'وصفة طبية',text});await markSharedAfterSuccess();$('formError').textContent=view==='admin'?'تم تسجيل مشاركة الوصفة.':'تم تجهيز الوصفة للمشاركة.';return}catch(error){if(error.name==='AbortError')return}}const target=`https://wa.me/${phone}?text=${encodeURIComponent(text)}`;if(popup)popup.location.href=target;else window.open(target,'_blank','noopener');await markSharedAfterSuccess();$('formError').textContent=view==='admin'?'تم تسجيل مشاركة الوصفة وفتح واتساب.':'تم فتح واتساب.'}catch(error){popup?.close();if(error.message!==$('formError').textContent)$('formError').textContent=error.message}}
async function init(){if(!patientId||!date||!/^clinic-(?:[1-9]|1[0-5])$/.test(clinic)){location.href='./';return}try{const state=await api(stateUrl);patient=(state.records||state.patients||[]).find(item=>String(item.id)===patientId)||{id:patientId,name:params.get('patientName')||'',file:params.get('file')||'',phone:params.get('phone')||'',nationalId:params.get('nationalId')||''};if(!patient.name&&!patient.file&&!patient.phone)throw new Error('لم يتم العثور على بيانات المريض المرتبطة بالوصفة.');$('patientTitle').textContent=patient.name||'—';$('patientFile').textContent=patient.file||'—';$('patientPhone').textContent=patient.phone||'—';$('visitDate').textContent=date;$('backLink').href=`./?view=${encodeURIComponent(view)}&clinic=${encodeURIComponent(clinic)}&date=${encodeURIComponent(date)}`;const rx=await api(prescriptionUrl());record=rx.record||null;restore(record?.prescription);renderHistory()}catch(error){$('formError').textContent=error.message}}
$('medicineCategory').addEventListener('change',updatePresetList);$('medicinePreset').addEventListener('change',()=>{const category=$('medicineCategory').value,preset=(CATALOG[category]||[]).find(item=>item.id===$('medicinePreset').value);if(preset)showEditor(category,preset)});$('addMedicineBtn').addEventListener('click',addOrUpdateMedicine);$('cancelMedicineEdit').addEventListener('click',resetEditor);$('selectedMedicines').addEventListener('click',event=>{const edit=event.target.closest('[data-edit-medicine]')?.dataset.editMedicine,remove=event.target.closest('[data-remove-medicine]')?.dataset.removeMedicine;if(edit!==undefined)editMedicine(Number(edit));if(remove!==undefined){selectedMedicines.splice(Number(remove),1);renderSelected()}});$('prescriptionHistory').addEventListener('click',event=>{const index=event.target.closest('[data-history-index]')?.dataset.historyIndex,entry=index!==undefined?record?.history?.[Number(index)]:null;if(entry?.prescription){restore(entry.prescription);window.scrollTo({top:0,behavior:'smooth'});$('formError').textContent='تم استعادة النسخة في المحرر؛ لن تُحفظ حتى تعتمدها مجددًا.'}});
$('rxForm').addEventListener('submit',async event=>{event.preventDefault();const button=$('saveBtn');button.disabled=true;try{await savePrescription('ready_for_admin');$('formError').textContent='تم اعتماد الوصفة من الطبيب وإرسالها إلى مركز الوصفات في الإدارة.'}catch(error){if(error.status===409)$('formError').textContent='توجد نسخة أحدث محفوظة. أعد تحميل الصفحة قبل التعديل.';else if(error.message!==$('formError').textContent)$('formError').textContent=error.message}finally{button.disabled=false}});$('shareBtn').addEventListener('click',sharePrescription);$('printBtn').addEventListener('click',()=>{const error=validate();$('formError').textContent=error;if(error)return;renderPreview();window.print()});['diagnosis','notes'].forEach(id=>$(id).addEventListener('input',()=>patient&&renderPreview()));init();
