'use strict';
const $=id=>document.getElementById(id);const params=new URLSearchParams(location.search);const patientId=params.get('patientId')||'',date=params.get('date')||'',clinic=params.get('clinic')||'clinic-1',view=params.get('view')||'clinic';let patient=null,record=null,selectedMedicines=[],editingMedicine=-1;
let language=params.get('lang')==='en'?'en':params.get('lang')==='ar'?'ar':localStorage.getItem('bestcare_lang')==='en'?'en':'ar';
const RX_TRANSLATIONS={
'الوصفة الطبية — عيادات أفضل عناية':'Prescription — Best Care Dental Clinics','← العودة':'← Back','الوصفة الطبية الإلكترونية':'Electronic prescription','عيادات أفضل عناية الاستشارية للأسنان':'Best Care Dental Clinics','شعار العيادة':'Clinic logo','المريض':'Patient','جارٍ تحميل البيانات…':'Loading patient data…','رقم الملف':'File number','الجوال':'Mobile','التاريخ':'Date','تنبيه إلزامي':'Mandatory notice','هذه أداة توثيق فقط. يختار الطبيب المخوّل الدواء والجرعة والتكرار والمدة من القائمة المعتمدة محليًا بعد المراجعة السريرية.':'Documentation only. An authorized clinician selects the medicine, dose, frequency, and duration from the locally approved list after clinical review.','المراجعة الطبية':'Medical review','أدخل السبب ثم أكد اكتمال المراجعة.':'Enter the reason, then confirm the review is complete.','التشخيص أو سبب الوصفة *':'Diagnosis or prescription reason *','راجعت التاريخ المرضي والحساسية والحمل ووظائف الكلى والكبد والتداخلات الدوائية في النظام المعتمد.':'I reviewed the medical history, allergies, pregnancy, kidney and liver function, and drug interactions in the approved system.','إضافة العلاج':'Add medication','اختر النوع ثم القالب؛ تبقى جميع الحقول قابلة للتعديل.':'Choose a category and template; all fields remain editable.','نوع العلاج':'Medication category','اختر النوع':'Choose category','مضاد حيوي':'Antibiotic','مسكن':'Analgesic','مضمضة':'Mouthwash','العلاج أو القالب':'Medication or template','اختر النوع أولًا':'Choose a category first','تفاصيل العلاج':'Medication details','لا تُعتمد أي قيمة قبل مراجعة الطبيب.':'No value is approved before clinician review.','اسم العلاج *':'Medication name *','التركيز':'Strength','الجرعة *':'Dose *','التكرار *':'Frequency *','المدة *':'Duration *','تعليمات الاستخدام':'Instructions for use','تُحدد بواسطة الطبيب':'Specified by clinician','إلغاء التعديل':'Cancel edit','＋ إضافة إلى الوصفة':'＋ Add to prescription','لم تتم إضافة علاج بعد.':'No medication added yet.','الملاحظات واعتماد الطبيب':'Notes and clinician approval','بعد الاعتماد تصل الوصفة إلى مركز الوصفات في صفحة الإدارة.':'After approval, the prescription appears in the administration prescription center.','ملاحظات إضافية':'Additional notes','أؤكد أن محتوى الوصفة راجعه وأقرّه طبيب مخوّل قبل إرساله للإدارة.':'I confirm an authorized clinician reviewed and approved this prescription before it is sent to administration.','اعتماد الطبيب وإرسالها لمركز الوصفات':'Approve and send to prescription center','مشاركة عبر واتساب':'Share via WhatsApp','طباعة / PDF':'Print / PDF','وصفات المريض السابقة':'Patient prescription history','سجل دائم مرتبط ببيانات المريض ويمكن استعادته بعد الاعتماد.':'A permanent record linked to the patient; prior versions can be restored.','لا توجد وصفات سابقة محفوظة.':'No saved prescriptions.','معاينة الوصفة':'Prescription preview','وصفة طبية':'Prescription','لا تُصرف هذه الوصفة إلا بعد اعتماد الطبيب · تاريخ الإصدار:':'Do not dispense without clinician approval · Issued:',
'علاج محفوظ سابقًا':'Previously saved medication','مضاد آخر معتمد محليًا':'Other locally approved antibiotic','مسكن معتمد محليًا':'Locally approved analgesic','مضمضة معتمدة محليًا':'Locally approved mouthwash','3 أيام':'3 days','5 أيام':'5 days','اختر العلاج':'Choose medication','تعديل':'Edit','حذف':'Delete','قالب محفوظ قابل للتعديل':'Editable saved template','وصفة سابقة — اختر النوع قبل الحفظ':'Previous prescription — choose a category before saving','حفظ تعديل العلاج':'Save medication changes','المريض:':'Patient:','رقم الملف:':'File number:','الجوال:':'Mobile:','التشخيص:':'Diagnosis:','ملاحظات:':'Notes:','مستخدم النظام':'System user','علاج':'medications','تمت مشاركتها مع المريض':'Shared with patient','معتمدة من الطبيب — لدى الإدارة':'Clinician-approved — with administration','استعادة هذه النسخة':'Restore this version',
'اختر نوع العلاج.':'Choose a medication category.','أدخل اسم العلاج.':'Enter the medication name.','أدخل الجرعة كما اعتمدها الطبيب.':'Enter the clinician-approved dose.','أدخل تكرار الاستخدام.':'Enter the frequency.','أدخل مدة الاستخدام.':'Enter the duration.','أدخل التشخيص أو سبب الوصفة.':'Enter a diagnosis or prescription reason.','أضف علاجًا واحدًا على الأقل.':'Add at least one medication.','أكد اكتمال المراجعة الطبية في النظام المعتمد.':'Confirm medical review in the approved system.','يلزم تأكيد الطبيب المخوّل قبل إرسال الوصفة.':'Authorized clinician confirmation is required before sending.','حسب وصف الطبيب':'As prescribed by clinician','انتهت الجلسة':'Session expired','تعذر إكمال الطلب':'Unable to complete the request','لم يتم العثور على بيانات المريض المرتبطة بالوصفة.':'Patient data linked to this prescription was not found.','تم تسجيل مشاركة الوصفة.':'Prescription sharing recorded.','تم تجهيز الوصفة للمشاركة.':'Prescription prepared for sharing.','تم تسجيل مشاركة الوصفة وفتح واتساب.':'Prescription sharing recorded and WhatsApp opened.','تم فتح واتساب.':'WhatsApp opened.','تم استعادة النسخة في المحرر؛ لن تُحفظ حتى تعتمدها مجددًا.':'The version was restored in the editor; it will not be saved until you approve it again.','تم اعتماد الوصفة من الطبيب وإرسالها إلى مركز الوصفات في الإدارة.':'The clinician approved the prescription and sent it to the administration prescription center.','توجد نسخة أحدث محفوظة. أعد تحميل الصفحة قبل التعديل.':'A newer version is saved. Reload before editing.','١':'1','٢':'2','٣':'3','مسودة — ليست استشارة طبية — للتوثيق فقط — يلزم توقيع طبيب مخوّل':'DRAFT — NOT MEDICAL ADVICE — DOCUMENTATION-ONLY — AUTHORIZED CLINICIAN SIGN-OFF REQUIRED'};
const tr=value=>language==='en'?(RX_TRANSLATIONS[value]||value):value;
const rxDate=value=>new Date(value).toLocaleString(language==='en'?'en-GB':'ar-SA');
function translatePage(){document.documentElement.lang=language==='en'?'en':'ar-SA';document.documentElement.dir=language==='en'?'ltr':'rtl';document.title=tr('الوصفة الطبية — عيادات أفضل عناية');const reverse=Object.fromEntries(Object.entries(RX_TRANSLATIONS).map(([ar,en])=>[en,ar]));const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement?.closest('#patientTitle,#patientFile,#patientPhone,#visitDate,#diagnosis,#notes,#selectedMedicines,#prescriptionHistory,#printPatient,#printDiagnosis,#printMedicines,#printNotes,#issuedAt,#formError'))continue;const raw=node.nodeValue,trim=raw.trim(),ar=reverse[trim]||trim,translation=tr(ar);if(trim&&translation!==trim)node.nodeValue=raw.replace(trim,translation)}document.querySelectorAll('[placeholder],[aria-label],[alt]').forEach(element=>{for(const attr of ['placeholder','aria-label','alt']){const value=element.getAttribute(attr);if(value){const ar=reverse[value]||value;element.setAttribute(attr,tr(ar))}}});$('languageToggle').textContent=language==='en'?'العربية':'English';$('languageToggle').setAttribute('aria-label',language==='en'?'Switch to Arabic':'التبديل إلى الإنجليزية')}
const NOTICE='DRAFT — NOT MEDICAL ADVICE — DOCUMENTATION-ONLY — AUTHORIZED CLINICIAN SIGN-OFF REQUIRED';
const CATEGORY_LABELS={antibiotic:'مضاد حيوي',analgesic:'مسكن',mouthwash:'مضمضة',legacy:'علاج محفوظ سابقًا'};
const CATALOG={
  antibiotic:[
    {id:'augmentin',label:'Amoxicillin / Clavulanate (Augmentin)',name:'Amoxicillin / Clavulanate (Augmentin)',strengths:['625 mg','1000 mg'],frequencies:['BID','TID'],durations:['3 أيام','5 أيام']},
    {id:'metronidazole',label:'Metronidazole',name:'Metronidazole',strengths:['500 mg'],frequencies:['BID','TID'],durations:['3 أيام','5 أيام']},
    {id:'custom-antibiotic',label:'مضاد آخر معتمد محليًا',name:''}
  ],
  analgesic:[{id:'custom-analgesic',label:'مسكن معتمد محليًا',name:''}],
  mouthwash:[{id:'custom-mouthwash',label:'مضمضة معتمدة محليًا',name:''}]
};
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const api=async(url,options={})=>{const response=await fetch(url,{credentials:'include',cache:'no-store',...options});const data=await response.json().catch(()=>({}));if(response.status===401){location.href=`./?returnTo=${encodeURIComponent(location.href)}`;throw new Error(tr('انتهت الجلسة'))}if(!response.ok){const error=new Error(data.error||tr('تعذر إكمال الطلب'));error.status=response.status;throw error}return data};
const stateUrl=`/api/state?date=${encodeURIComponent(date)}&clinic=${encodeURIComponent(clinic)}`;
const normalizePhone=value=>String(value||'').replace(/\D/g,'').replace(/^00966/,'0').replace(/^966/,'0').replace(/^5(?=\d{8}$)/,'05');
const nameScore=value=>{const text=String(value||'').trim();return text?text.split(/\s+/).filter(Boolean).length*100+text.length:0};
const preferCompleteName=(current,stored)=>nameScore(stored)>nameScore(current)?String(stored||'').trim():String(current||'').trim();
function prescriptionUrl(extra={}){const query=new URLSearchParams({patientId,date,clinic,file:String(patient?.file||''),phone:normalizePhone(patient?.phone),nationalId:String(patient?.nationalId||''),...extra});return`/api/prescriptions?${query.toString()}`}
function setOptions(node,values=[]){node.innerHTML=(values||[]).map(value=>`<option value="${esc(tr(value))}"></option>`).join('')}
function resetEditor(){editingMedicine=-1;$('medicineEditor').hidden=true;$('medicineCategory').value='';$('medicinePreset').innerHTML=`<option value="">${tr('اختر النوع أولًا')}</option>`;$('medicinePreset').disabled=true;['medicineName','medicineStrength','medicineDose','medicineFrequency','medicineDuration','medicineInstructions'].forEach(id=>$(id).value='');$('cancelMedicineEdit').hidden=true;$('addMedicineBtn').textContent=tr('＋ إضافة إلى الوصفة')}
function showEditor(category,preset={}){$('medicineEditor').hidden=false;$('medicineEditorTitle').textContent=tr(preset.label||CATEGORY_LABELS[category]||'تفاصيل العلاج');$('medicineName').value=preset.name||'';$('medicineStrength').value='';$('medicineDose').value='';$('medicineFrequency').value='';$('medicineDuration').value='';$('medicineInstructions').value=preset.instructions||'';setOptions($('strengthSuggestions'),preset.strengths);setOptions($('frequencySuggestions'),preset.frequencies);setOptions($('durationSuggestions'),preset.durations);$('medicineName').focus()}
function updatePresetList(){const category=$('medicineCategory').value,items=CATALOG[category]||[];$('medicinePreset').disabled=!category;$('medicinePreset').innerHTML=`<option value="">${tr(category?'اختر العلاج':'اختر النوع أولًا')}</option>${items.map(item=>`<option value="${esc(item.id)}">${esc(tr(item.label))}</option>`).join('')}`;$('medicineEditor').hidden=true}
function editorMedicine(){const category=$('medicineCategory').value;return{category,template:$('medicinePreset').value||'custom',name:$('medicineName').value.trim(),strength:$('medicineStrength').value.trim(),dose:$('medicineDose').value.trim(),frequency:$('medicineFrequency').value.trim(),duration:$('medicineDuration').value.trim(),instructions:$('medicineInstructions').value.trim()}}
function editorError(medicine){if(!medicine.category)return tr('اختر نوع العلاج.');if(!medicine.name)return tr('أدخل اسم العلاج.');if(!medicine.dose)return tr('أدخل الجرعة كما اعتمدها الطبيب.');if(!medicine.frequency)return tr('أدخل تكرار الاستخدام.');if(!medicine.duration)return tr('أدخل مدة الاستخدام.');return''}
function renderSelected(){const target=$('selectedMedicines');if(!selectedMedicines.length){target.innerHTML=`<div class="empty-state">${tr('لم تتم إضافة علاج بعد.')}</div>`;renderPreview();return}target.innerHTML=selectedMedicines.map((medicine,index)=>`<article class="selected-medicine"><span class="med-icon" aria-hidden="true">💊</span><div><strong>${esc(medicine.name)} ${esc(medicine.strength)}</strong><small>${esc(tr(CATEGORY_LABELS[medicine.category]||CATEGORY_LABELS.legacy))} · ${esc(tr(medicine.dose))} · ${esc(tr(medicine.frequency))} · ${esc(tr(medicine.duration))}</small>${medicine.instructions?`<small>${esc(tr(medicine.instructions))}</small>`:''}</div><div class="selected-medicine-actions"><button type="button" data-edit-medicine="${index}">${tr('تعديل')}</button><button type="button" class="danger" data-remove-medicine="${index}">${tr('حذف')}</button></div></article>`).join('');renderPreview()}
function addOrUpdateMedicine(){const medicine=editorMedicine(),error=editorError(medicine);$('formError').textContent=error;if(error)return;if(editingMedicine>=0)selectedMedicines[editingMedicine]=medicine;else selectedMedicines.push(medicine);resetEditor();renderSelected()}
function editMedicine(index){const medicine=selectedMedicines[index];if(!medicine)return;editingMedicine=index;const supported=CATALOG[medicine.category]?medicine.category:'';$('medicineCategory').value=supported;$('medicinePreset').disabled=!supported;$('medicinePreset').innerHTML=supported?`<option value="custom">${tr('قالب محفوظ قابل للتعديل')}</option>`:`<option value="">${tr('وصفة سابقة — اختر النوع قبل الحفظ')}</option>`;$('medicinePreset').value=supported?'custom':'';$('medicineEditor').hidden=false;$('medicineEditorTitle').textContent=`${tr('تعديل')} ${medicine.name}`;['Name','Strength','Dose','Frequency','Duration','Instructions'].forEach(field=>$(`medicine${field}`).value=medicine[field.toLowerCase()]||'');$('cancelMedicineEdit').hidden=false;$('addMedicineBtn').textContent=tr('حفظ تعديل العلاج');$('medicineName').focus()}
function validate(){if(!$('diagnosis').value.trim())return tr('أدخل التشخيص أو سبب الوصفة.');if(!selectedMedicines.length)return tr('أضف علاجًا واحدًا على الأقل.');const incomplete=selectedMedicines.find(editorError);if(incomplete)return language==='en'?`Review ${incomplete.name||'medication'}: ${editorError(incomplete)}`:`راجع بيانات ${incomplete.name||'العلاج'}: ${editorError(incomplete)}`;if(!$('medicalReview').checked)return tr('أكد اكتمال المراجعة الطبية في النظام المعتمد.');if(!$('doctorConfirm').checked)return tr('يلزم تأكيد الطبيب المخوّل قبل إرسال الوصفة.');return''}
function payload(status='ready_for_admin'){return{patient:{id:patientId,name:patient?.name||'',file:patient?.file||'',phone:normalizePhone(patient?.phone),nationalId:patient?.nationalId||''},diagnosis:$('diagnosis').value.trim(),medicines:selectedMedicines.map(item=>({...item})),notes:$('notes').value.trim(),medicalReview:Boolean($('medicalReview').checked),doctorConfirmed:Boolean($('doctorConfirm').checked),notice:NOTICE,status,issuedAt:new Date().toISOString(),sourcePatientId:patientId,sourceDate:date}}
function renderPreview(data=payload(record?.status||'ready_for_admin')){const meds=data.medicines||[];$('printPatient').innerHTML=`<b>${tr('المريض:')}</b> ${esc(patient?.name||data.patient?.name||'—')} &nbsp; <b>${tr('رقم الملف:')}</b> ${esc(patient?.file||data.patient?.file||'—')} &nbsp; <b>${tr('الجوال:')}</b> ${esc(patient?.phone||data.patient?.phone||'—')}`;$('printDiagnosis').innerHTML=`<b>${tr('التشخيص:')}</b> ${esc(data.diagnosis||'—')}`;$('printMedicines').innerHTML=meds.map(m=>`<li><b>${esc(m.name)} ${esc(m.strength)}</b> — ${esc(tr(m.dose))}${language==='en'?', ':'، '}${esc(tr(m.frequency))}${language==='en'?', ':'، '}${esc(tr(m.duration))}<br>${esc(tr(m.instructions))}</li>`).join('');$('printNotes').innerHTML=data.notes?`<b>${tr('ملاحظات:')}</b> ${esc(data.notes)}`:'';$('issuedAt').textContent=rxDate(data.issuedAt||Date.now())}
function restore(data){if(!data)return;$('diagnosis').value=data.diagnosis||'';$('notes').value=data.notes||'';$('medicalReview').checked=Boolean(data.medicalReview);$('doctorConfirm').checked=Boolean(data.doctorConfirmed||data.status==='issued'||data.status==='ready_for_admin'||data.status==='shared');selectedMedicines=(data.medicines||[]).map(medicine=>({category:medicine.category||(['augmentin','metronidazole'].includes(medicine.template)?'antibiotic':'legacy'),template:medicine.template||'custom',name:medicine.name||'',strength:medicine.strength||'',dose:medicine.dose||'حسب وصف الطبيب',frequency:medicine.frequency||'',duration:medicine.duration||'',instructions:medicine.instructions||''}));renderSelected();renderPreview(data)}
function historyEntries(){if(Array.isArray(record?.history)&&record.history.length)return record.history;return record?.prescription?[{at:record.updatedAt,status:record.status,prescription:record.prescription,by:record.updatedBy}]:[]}
function renderHistory(){const target=$('prescriptionHistory'),history=historyEntries().slice().reverse();if(!history.length){target.innerHTML=`<div class="empty-state">${tr('لا توجد وصفات سابقة محفوظة.')}</div>`;return}target.innerHTML=`<div class="history-list">${history.map((entry,index)=>`<article class="history-item"><div><strong>${rxDate(Number(entry.at||Date.now()))}</strong><small>${esc(entry.by||tr('مستخدم النظام'))} · ${(entry.prescription?.medicines||[]).length} ${tr('علاج')}</small><span class="history-status ${entry.status==='shared'?'shared':''}">${tr(entry.status==='shared'?'تمت مشاركتها مع المريض':'معتمدة من الطبيب — لدى الإدارة')}</span></div><div class="history-actions"><button type="button" data-history-index="${history.length-1-index}">${tr('استعادة هذه النسخة')}</button></div></article>`).join('')}</div>`}
async function savePrescription(status='ready_for_admin'){const error=validate();$('formError').textContent=error;if(error)throw new Error(error);const data=await api(prescriptionUrl(),{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({prescription:payload(status),expectedRevision:Number(record?.revision||0)})});record=data.record;renderHistory();renderPreview(record.prescription);return data.record}
function whatsappText(data){const en=language==='en',list=(data.medicines||[]).map((m,i)=>`${i+1}. ${m.name}${m.strength?` — ${m.strength}`:''}\n${en?'Dose':'الجرعة'}: ${tr(m.dose)}\n${en?'Frequency':'التكرار'}: ${tr(m.frequency)}\n${en?'Duration':'المدة'}: ${tr(m.duration)}${m.instructions?`\n${en?'Instructions':'التعليمات'}: ${tr(m.instructions)}`:''}`).join('\n\n');return en?`Attached is the clinician-approved prescription\nPatient: ${patient.name}\nFile number: ${patient.file}\n\n${list}\n\nUse medicines only as directed by the clinician.`:`مرفق لكم الوصفة الطبية المعتمدة من الطبيب\nالمريض: ${patient.name}\nرقم الملف: ${patient.file}\n\n${list}\n\nتُستخدم الأدوية حسب تعليمات الطبيب المدوّنة فقط.`}
async function markSharedAfterSuccess(){if(view!=='admin')return;await savePrescription('shared')}
async function sharePrescription(){const popup=!navigator.share?window.open('about:blank','_blank'):null;try{const saved=await savePrescription('ready_for_admin'),text=whatsappText(saved.prescription),phone=String(patient.phone||'').replace(/\D/g,'').replace(/^0/,'966');if(navigator.share){try{await navigator.share({title:tr('وصفة طبية'),text});await markSharedAfterSuccess();$('formError').textContent=tr(view==='admin'?'تم تسجيل مشاركة الوصفة.':'تم تجهيز الوصفة للمشاركة.');return}catch(error){if(error.name==='AbortError')return}}const target=`https://wa.me/${phone}?text=${encodeURIComponent(text)}`;if(popup)popup.location.href=target;else window.open(target,'_blank','noopener');await markSharedAfterSuccess();$('formError').textContent=tr(view==='admin'?'تم تسجيل مشاركة الوصفة وفتح واتساب.':'تم فتح واتساب.')}catch(error){popup?.close();if(error.message!==$('formError').textContent)$('formError').textContent=error.message}}
async function init(){
  if(!patientId||!date||!/^clinic-(?:[1-9]|1[0-5])$/.test(clinic)){location.href='./';return}
  try{
    const state=await api(stateUrl);
    patient=(state.records||state.patients||[]).find(item=>String(item.id)===patientId)||{id:patientId,name:params.get('patientName')||'',file:params.get('file')||'',phone:params.get('phone')||'',nationalId:params.get('nationalId')||''};
    if(!patient.name&&!patient.file&&!patient.phone)throw new Error(tr('لم يتم العثور على بيانات المريض المرتبطة بالوصفة.'));
    const rx=await api(prescriptionUrl());
    record=rx.record||null;
    const storedPatient=record?.prescription?.patient||{};
    patient={...patient,name:preferCompleteName(patient.name,storedPatient.name),file:patient.file||storedPatient.file||'',phone:patient.phone||storedPatient.phone||'',nationalId:patient.nationalId||storedPatient.nationalId||''};
    $('patientTitle').textContent=patient.name||'—';
    $('patientFile').textContent=patient.file||'—';
    $('patientPhone').textContent=patient.phone||'—';
    $('visitDate').textContent=new Date(`${date}T12:00:00`).toLocaleDateString(language==='en'?'en-GB':'ar-SA-u-ca-gregory');
    $('backLink').href=`./?view=${encodeURIComponent(view)}&clinic=${encodeURIComponent(clinic)}&date=${encodeURIComponent(date)}&lang=${language}`;
    restore(record?.prescription);
    renderHistory();
  }catch(error){$('formError').textContent=error.message}
}
$('medicineCategory').addEventListener('change',updatePresetList);$('medicinePreset').addEventListener('change',()=>{const category=$('medicineCategory').value,preset=(CATALOG[category]||[]).find(item=>item.id===$('medicinePreset').value);if(preset)showEditor(category,preset)});$('addMedicineBtn').addEventListener('click',addOrUpdateMedicine);$('cancelMedicineEdit').addEventListener('click',resetEditor);$('selectedMedicines').addEventListener('click',event=>{const edit=event.target.closest('[data-edit-medicine]')?.dataset.editMedicine,remove=event.target.closest('[data-remove-medicine]')?.dataset.removeMedicine;if(edit!==undefined)editMedicine(Number(edit));if(remove!==undefined){selectedMedicines.splice(Number(remove),1);renderSelected()}});$('prescriptionHistory').addEventListener('click',event=>{const index=event.target.closest('[data-history-index]')?.dataset.historyIndex,entry=index!==undefined?record?.history?.[Number(index)]:null;if(entry?.prescription){restore(entry.prescription);window.scrollTo({top:0,behavior:'smooth'});$('formError').textContent=tr('تم استعادة النسخة في المحرر؛ لن تُحفظ حتى تعتمدها مجددًا.')}});
$('rxForm').addEventListener('submit',async event=>{event.preventDefault();const button=$('saveBtn');button.disabled=true;try{await savePrescription('ready_for_admin');$('formError').textContent=tr('تم اعتماد الوصفة من الطبيب وإرسالها إلى مركز الوصفات في الإدارة.')}catch(error){if(error.status===409)$('formError').textContent=tr('توجد نسخة أحدث محفوظة. أعد تحميل الصفحة قبل التعديل.');else if(error.message!==$('formError').textContent)$('formError').textContent=error.message}finally{button.disabled=false}});$('shareBtn').addEventListener('click',sharePrescription);$('printBtn').addEventListener('click',()=>{const error=validate();$('formError').textContent=error;if(error)return;renderPreview();window.print()});['diagnosis','notes'].forEach(id=>$(id).addEventListener('input',()=>patient&&renderPreview()));$('languageToggle').addEventListener('click',()=>{language=language==='en'?'ar':'en';localStorage.setItem('bestcare_lang',language);const url=new URL(location.href);url.searchParams.set('lang',language);history.replaceState(null,'',url);translatePage();renderSelected();renderHistory();if(patient){$('visitDate').textContent=new Date(`${date}T12:00:00`).toLocaleDateString(language==='en'?'en-GB':'ar-SA-u-ca-gregory');renderPreview()}$('backLink').href=`./?view=${encodeURIComponent(view)}&clinic=${encodeURIComponent(clinic)}&date=${encodeURIComponent(date)}&lang=${language}`});translatePage();init();
