'use strict';
const $=id=>document.getElementById(id);const params=new URLSearchParams(location.search);const patientId=params.get('patientId')||'',date=params.get('date')||'',clinic=params.get('clinic')||'clinic-1',view=params.get('view')||'clinic';let patient=null,record=null;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const api=async(url,options={})=>{const response=await fetch(url,{credentials:'include',cache:'no-store',...options});const data=await response.json().catch(()=>({}));if(response.status===401){location.href=`./?returnTo=${encodeURIComponent(location.href)}`;throw new Error('انتهت الجلسة')}if(!response.ok)throw new Error(data.error||'تعذر إكمال الطلب');return data};
const stateUrl=`/api/state?date=${encodeURIComponent(date)}&clinic=${encodeURIComponent(clinic)}`;const rxUrl=`/api/prescriptions?patientId=${encodeURIComponent(patientId)}&date=${encodeURIComponent(date)}&clinic=${encodeURIComponent(clinic)}`;
function medicineFrom(prefix,template){return{template,name:$(`${prefix}Name`).value.trim(),strength:$(`${prefix}Strength`).value.trim(),frequency:$(`${prefix}Frequency`).value.trim(),duration:`${Math.max(1,Math.min(30,Number($(`${prefix}Days`).value)||1))} أيام`,instructions:$(`${prefix}Instructions`).value.trim()}}
function medicines(){const items=[];if($('augmentinEnabled').checked)items.push(medicineFrom('augmentin','augmentin'));if($('metronidazoleEnabled').checked)items.push(medicineFrom('metronidazole','metronidazole'));if($('prednisoloneEnabled').checked)items.push(medicineFrom('prednisolone','prednisolone'));if($('otherEnabled').checked)items.push(medicineFrom('other','other'));return items.filter(item=>item.name)}
function validate(){if(!$('diagnosis').value.trim())return'أدخل التشخيص أو سبب الوصفة.';const meds=medicines();if(!meds.length)return'اختر دواءً واحدًا على الأقل.';if(!$('medicalReview').checked)return'أكد مراجعة التاريخ المرضي والحساسية والتداخلات.';if($('prednisoloneEnabled').checked&&!$('steroidConfirm').checked)return'أكد مراجعة نظام Prednisolone قبل الإصدار.';if(!$('doctorConfirm').checked)return'يلزم تأكيد الطبيب المخوّل قبل الإصدار.';return''}
function payload(){return{patient:{id:patientId,name:patient?.name||'',file:patient?.file||'',phone:patient?.phone||''},diagnosis:$('diagnosis').value.trim(),medicines:medicines(),notes:$('notes').value.trim(),medicalReview:true,status:'issued',issuedAt:new Date().toISOString()}}
function renderPreview(data=payload()){const meds=data.medicines||[];$('printPatient').innerHTML=`<b>المريض:</b> ${esc(patient?.name||'—')} &nbsp; <b>رقم الملف:</b> ${esc(patient?.file||'—')} &nbsp; <b>الجوال:</b> ${esc(patient?.phone||'—')}`;$('printDiagnosis').innerHTML=`<b>التشخيص:</b> ${esc(data.diagnosis||'—')}`;$('printMedicines').innerHTML=meds.map(m=>`<li><b>${esc(m.name)} ${esc(m.strength)}</b> — ${esc(m.frequency)}، ${esc(m.duration)}<br>${esc(m.instructions)}</li>`).join('');$('printNotes').innerHTML=data.notes?`<b>ملاحظات:</b> ${esc(data.notes)}`:'';$('issuedAt').textContent=new Date(data.issuedAt||Date.now()).toLocaleString('ar-SA')}
function restoreMedicine(med,index){let prefix=med.template;if(!['augmentin','metronidazole','prednisolone','other'].includes(prefix)){prefix=med.name.includes('Clavulanate')?'augmentin':med.name.includes('Metronidazole')?'metronidazole':med.name.includes('Prednisolone')?'prednisolone':'other'}if(prefix==='other'&&index>0)return;$(`${prefix}Enabled`).checked=true;$(`${prefix}Name`).value=med.name||'';$(`${prefix}Strength`).value=med.strength||'';$(`${prefix}Frequency`).value=med.frequency||'';$(`${prefix}Days`).value=parseInt(med.duration)||1;$(`${prefix}Instructions`).value=med.instructions||''}
function restore(data){if(!data)return;$('diagnosis').value=data.diagnosis||'';$('notes').value=data.notes||'';(data.medicines||[]).forEach(restoreMedicine);renderPreview(data)}
async function init(){if(!patientId||!date||!/^clinic-(?:[1-9]|1[0-5])$/.test(clinic)){location.href='./';return}try{const [state,rx]=await Promise.all([api(stateUrl),api(rxUrl)]);patient=(state.records||state.patients||[]).find(item=>String(item.id)===patientId);if(!patient)throw new Error('لم يتم العثور على المريض في قائمة هذا اليوم.');$('patientTitle').textContent=patient.name||'—';$('patientFile').textContent=patient.file||'—';$('patientPhone').textContent=patient.phone||'—';$('visitDate').textContent=date;$('backLink').href=`./?view=${encodeURIComponent(view)}&clinic=${encodeURIComponent(clinic)}&date=${encodeURIComponent(date)}`;record=rx.record||null;restore(record?.prescription)}catch(error){$('formError').textContent=error.message}}
$('rxForm').addEventListener('submit',async event=>{event.preventDefault();const error=validate();$('formError').textContent=error;if(error)return;const button=$('saveBtn');button.disabled=true;try{const prescription=payload();const data=await api(rxUrl,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({prescription})});record=data.record;renderPreview(prescription);$('formError').textContent='تم حفظ وإصدار الوصفة.'}catch(error){$('formError').textContent=error.message}finally{button.disabled=false}});
$('shareBtn').addEventListener('click',async()=>{const error=validate();$('formError').textContent=error;if(error)return;const data=payload();renderPreview(data);const list=data.medicines.map((m,i)=>`${i+1}. ${m.name} ${m.strength}\n${m.frequency} لمدة ${m.duration}\n${m.instructions}`).join('\n\n');const text=`وصفة طبية للمريض ${patient.name}\nرقم الملف: ${patient.file}\n\n${list}\n\nملاحظة: تُستخدم الأدوية حسب وصف الطبيب فقط.`;const phone=String(patient.phone||'').replace(/\D/g,'').replace(/^0/,'966');if(navigator.share){try{await navigator.share({title:'وصفة طبية',text});return}catch(error){if(error.name==='AbortError')return}}window.open(`https://wa.me/${phone}?text=${encodeURIComponent(text)}`,'_blank','noopener')});
$('printBtn').addEventListener('click',()=>{const error=validate();$('formError').textContent=error;if(error)return;renderPreview();window.print()});
document.querySelectorAll('input,select,textarea').forEach(node=>node.addEventListener('change',()=>{if(patient)renderPreview()}));init();
