(()=>{'use strict';
const $=id=>document.getElementById(id),API='/api/treatment-plan-registry',STATUSES=['draft','submitted','patient_accepted','approved','approved_signed','rejected'];
const LABELS={draft:'مسودة غير معتمدة',submitted:'اعتمدها الطبيب · لدى الإدارة',patient_accepted:'وافق ووقّع',approved:'خطة معتمدة',approved_signed:'خطة معتمدة وموقعة',rejected:'تحتاج تعديل'};
let records={},aliases={},clinics=[];
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const request=async(url,options={})=>fetch(url,{credentials:'include',...options});
const isZero=value=>/^0+$/.test(String(value??'').trim());
const entries=()=>Object.entries(records).map(([canonical,record])=>({canonical,record})).sort((a,b)=>Number(b.record.updatedAt||0)-Number(a.record.updatedAt||0));
const clinicLabel=id=>{const clinic=clinics.find(item=>item.id===id);if(!clinic)return`العيادة ${Math.max(1,Math.min(15,Number(String(id||'clinic-1').split('-')[1])||1))}`;return`${clinic.name||'العيادة'}${clinic.roomNumber?` · رقم ${clinic.roomNumber}`:''}${clinic.doctorName?` · د. ${clinic.doctorName}`:''}`};
function syncClinics(){const current=$('clinicFilter').value||'all',ids=[...new Set(entries().map(item=>item.record.clinicId).filter(Boolean))].sort();$('clinicFilter').innerHTML='<option value="all">جميع العيادات</option>'+ids.map(id=>`<option value="${esc(id)}">${clinicLabel(id)}</option>`).join('');$('clinicFilter').value=ids.includes(current)?current:'all'}
function render(){
  syncClinics();const all=entries(),pending=all.filter(({record})=>!['approved','approved_signed'].includes(record.status)),zero=all.filter(({canonical,record})=>isZero(record.fileNo)||/^file:0+$/i.test(canonical));
  $('totalCount').textContent=all.length;$('pendingCount').textContent=pending.length;$('approvedCount').textContent=all.filter(({record})=>record.status==='approved_signed').length;$('zeroCount').textContent=zero.length;
  const q=$('searchInput').value.trim().toLowerCase(),clinic=$('clinicFilter').value,status=$('statusFilter').value;
  const visible=all.filter(({record})=>clinic==='all'||record.clinicId===clinic).filter(({record})=>status==='all'||status==='unapproved'&&!['approved','approved_signed'].includes(record.status)||record.status===status).filter(({record})=>!q||`${record.fullName||''} ${record.fileNo||''} ${record.mobile||''} ${record.planNo||''}`.toLowerCase().includes(q));
  if(!visible.length){$('planList').innerHTML='<p class="empty">لا توجد خطط مطابقة للتصفية.</p>';return}
  $('planList').innerHTML=visible.map(({canonical,record})=>{const pending=!['approved','approved_signed'].includes(record.status),zeroFile=isZero(record.fileNo)||/^file:0+$/i.test(canonical),canOpen=record.sourcePatientId&&/^\d{4}-\d{2}-\d{2}$/.test(record.sourceDate||'');return`<article class="card ${pending?'pending':''} ${zeroFile?'zero':''}" data-key="${esc(canonical)}"><div class="patient"><strong>${esc(record.fullName||'مريض بدون اسم')}</strong><small>${record.planNo?`خطة ${esc(record.planNo)} · `:''}ملف ${esc(record.fileNo||'غير مسجل')}${record.mobile?` · ${esc(record.mobile)}`:''}</small>${zeroFile?'<span class="warning">⚠ رقم الملف 0 مشترك — يجب تصحيحه</span>':''}</div><div class="clinic"><strong>${esc(clinicLabel(record.clinicId))}</strong><small>${record.updatedAt?new Date(record.updatedAt).toLocaleString('ar-SA-u-ca-gregory-nu-latn'):'—'}</small></div><label class="status">حالة الاعتماد<select data-status="${esc(canonical)}">${STATUSES.map(value=>`<option value="${value}" ${record.status===value?'selected':''}>${esc(LABELS[value])}</option>`).join('')}</select></label><div class="card-actions"><button type="button" data-open="${esc(canonical)}" ${canOpen?'':'disabled'}>فتح وتعديل</button><button type="button" class="danger" data-delete="${esc(canonical)}">حذف</button></div></article>`}).join('');
  const focus=new URLSearchParams(location.search).get('focus');if(focus){const node=[...document.querySelectorAll('[data-key]')].find(item=>item.dataset.key===focus);node?.scrollIntoView({block:'center'});node?.animate?.([{boxShadow:'0 0 0 0 rgba(49,95,133,0)'},{boxShadow:'0 0 0 8px rgba(49,95,133,.2)'},{boxShadow:'0 8px 23px rgba(38,77,103,.07)'}],{duration:1400})}
}
async function load(){try{$('errorBox').hidden=true;const [planResponse,clinicResponse]=await Promise.all([request(`${API}?clinic=clinic-1&_=${Date.now()}`),request('/api/clinics')]),data=await planResponse.json().catch(()=>({})),clinicData=await clinicResponse.json().catch(()=>({}));if(planResponse.status===401)throw new Error('يلزم تسجيل الدخول من لوحة الإدارة أولًا.');if(!planResponse.ok)throw new Error(data.error||'تعذر تحميل الخطط');records=data.records||{};aliases=data.aliases||{};clinics=Array.isArray(clinicData.clinics)?clinicData.clinics:[];render()}catch(error){$('errorBox').textContent=error.message;$('errorBox').hidden=false;$('planList').innerHTML='<p class="empty"><a class="btn" href="./?view=admin">فتح صفحة الدخول</a></p>'}}
function openPlan(canonical){const record=records[canonical];if(!record)return;localStorage.setItem(`bestcare_treatment_source_${record.sourcePatientId}`,JSON.stringify({__bestcareSource:1,expiresAt:Date.now()+12*60*60*1000,source:{id:record.sourcePatientId,name:record.fullName||'',file:record.fileNo||'',phone:record.mobile||'',nationalId:record.nationalId||'',date:record.sourceDate,view:'admin',returnUrl:location.href}}));location.href=`./treatment-plan.html?${new URLSearchParams({patientId:record.sourcePatientId,date:record.sourceDate,clinic:record.clinicId||'clinic-1',view:'admin'})}`}
function updateMeta(plan,status){const now=Date.now();plan.meta=plan.meta&&typeof plan.meta==='object'?plan.meta:{};plan.meta.status=status;if(status==='draft')Object.assign(plan.meta,{doctorApprovedAt:0,doctorApprovedBy:'',submittedAt:0,patientAcceptedAt:0,patientAcceptedBy:'',approvedAt:0,approvedBy:'',rejectedAt:0,rejectedBy:'',rejectionReason:''});else if(status==='submitted')Object.assign(plan.meta,{doctorApprovedAt:now,doctorApprovedBy:'الإدارة',submittedAt:now,patientAcceptedAt:0,patientAcceptedBy:'',approvedAt:0,approvedBy:'',rejectedAt:0,rejectedBy:'',rejectionReason:''});else if(status==='patient_accepted')Object.assign(plan.meta,{patientAcceptedAt:now,patientAcceptedBy:'الإدارة',approvedAt:0,approvedBy:'',rejectedAt:0,rejectedBy:'',rejectionReason:''});else if(['approved','approved_signed'].includes(status))Object.assign(plan.meta,{approvedAt:now,approvedBy:'الإدارة',rejectedAt:0,rejectedBy:'',rejectionReason:'',revision:Math.max(1,Number(plan.meta.revision||1)+1)});else if(status==='rejected')Object.assign(plan.meta,{rejectedAt:now,rejectedBy:'الإدارة',rejectionReason:'تحتاج الخطة إلى مراجعة الإجراءات أو الأسعار.',patientAcceptedAt:0,patientAcceptedBy:'',approvedAt:0,approvedBy:''})}
async function changeStatus(canonical,status,select){const record=records[canonical],previous=record?.status;if(!record||status===previous)return;select.disabled=true;try{const params=new URLSearchParams({patientId:record.sourcePatientId,date:record.sourceDate,clinic:record.clinicId||'clinic-1'}),loaded=await request(`/api/treatment-plan?${params}`),data=await loaded.json();if(!loaded.ok||!data.exists||!data.plan)throw new Error('تعذر العثور على ملف الخطة الكامل');updateMeta(data.plan,status);const saved=await request(`/api/treatment-plan?${params}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({plan:data.plan})});if(!saved.ok)throw new Error('تعذر حفظ الخطة');const indexed=await request(`${API}?clinic=${encodeURIComponent(record.clinicId||'clinic-1')}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({patient:{fullName:record.fullName,fileNo:record.fileNo,mobile:record.mobile,nationalId:record.nationalId},status,planNo:record.planNo,sourcePatientId:record.sourcePatientId,sourceDate:record.sourceDate})});if(!indexed.ok)throw new Error('تعذر تحديث فهرس الخطط');await load()}catch(error){select.value=previous;alert(error.message)}finally{select.disabled=false}}
async function removePlan(canonical){const record=records[canonical];if(!record||!confirm(`حذف خطة ${record.fullName||'المريض'} نهائيًا؟`))return;try{const response=await request(`${API}?clinic=${encodeURIComponent(record.clinicId||'clinic-1')}`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({canonical})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'تعذر حذف الخطة');await load()}catch(error){alert(error.message)}}
$('refreshBtn').addEventListener('click',load);$('searchInput').addEventListener('input',render);$('clinicFilter').addEventListener('change',render);$('statusFilter').addEventListener('change',render);$('clearFilters').addEventListener('click',()=>{$('searchInput').value='';$('clinicFilter').value='all';$('statusFilter').value='all';render()});$('planList').addEventListener('click',event=>{const open=event.target.closest('[data-open]')?.dataset.open,remove=event.target.closest('[data-delete]')?.dataset.delete;if(open)openPlan(open);if(remove)removePlan(remove)});$('planList').addEventListener('change',event=>{const key=event.target.dataset.status;if(key)changeStatus(key,event.target.value,event.target)});load();
})();
