(()=>{'use strict';
const $=id=>document.getElementById(id),API='/api/treatment-plan-registry',STATUSES=['draft','submitted','patient_accepted','approved','approved_signed','rejected','cancelled'];
const urlParams=new URLSearchParams(location.search);let language=urlParams.get('lang')==='en'?'en':urlParams.get('lang')==='ar'?'ar':localStorage.getItem('bestcare_lang')==='en'?'en':'ar';
const PLAN_TRANSLATIONS={'مركز الخطط العلاجية | أفضل عناية':'Treatment Plans Center | Best Care','شعار أفضل عناية':'Best Care logo','مركز الخطط العلاجية':'Treatment Plans Center','متابعة الاعتماد والتصحيح والسجل الدائم لكل مريض':'Track approvals, corrections, and permanent patient records','العودة للإدارة':'Back to administration','تحديث':'Refresh','إجمالي الخطط':'Total plans','تحتاج إجراء':'Action needed','معتمدة وموقعة':'Approved and signed','رقم ملف يحتاج تصحيحًا':'File number needs correction','دليل ألوان حالات الخطط':'Plan status color key','مسودة':'Draft','لدى الإدارة':'With administration','وافق المريض':'Patient accepted','معتمدة':'Approved','تحتاج تعديلًا':'Needs changes','ملغاة':'Cancelled','بحث بالاسم أو الملف أو الجوال أو رقم الخطة':'Search name, file, mobile, or plan number','جميع العيادات':'All clinics','جميع الحالات':'All statuses','غير المعتمدة فقط':'Unapproved only','الخطط الملغاة':'Cancelled plans','مسح التصفية':'Clear filters','جارٍ تحميل الخطط العلاجية…':'Loading treatment plans…','قيد إعداد الإدارة':'Being prepared by administration','جاهزة لمشاركة وتوقيع المريض':'Ready to share for patient signature','وافق ووقّع':'Accepted and signed','خطة معتمدة':'Approved plan','خطة معتمدة وموقعة':'Approved and signed plan','تحتاج تصحيح':'Needs correction','خطة ملغاة':'Cancelled plan','موافقة التصوير غير موثقة':'Imaging consent not documented','المريض لم يوقّع على موافقة التصوير':'Patient did not sign imaging consent','العيادة':'Clinic','رقم':'Room','د.':'Dr.','لا توجد خطط مطابقة للتصفية.':'No plans match these filters.','مريض بدون اسم':'Unnamed patient','خطة':'Plan','ملف':'File','غير مسجل':'Not recorded','رقم الملف 0 مشترك — يجب تصحيحه':'Shared file number 0 — correction required','الخطة جاهزة للمشاركة وإرسال رابط توقيع المريض':'Plan is ready to share with patient signature link','سبب الإلغاء:':'Cancellation reason:','حالة الاعتماد':'Approval status','مشاركة الخطة والتوقيع':'Share plan and signature','فتح وتعديل':'Open and edit','حذف':'Delete','يلزم تسجيل الدخول من لوحة الإدارة أولًا.':'Sign in through administration first.','تعذر تحميل الخطط':'Could not load plans','فتح صفحة الدخول':'Open sign-in page','لا يمكن اعتماد الخطة يدويًا. افتح الخطة وشارك رابط التوقيع؛ يتم الاعتماد النهائي تلقائيًا بعد توقيع المريض.':'The plan cannot be approved manually. Open it and share the signature link; final approval follows the patient signature.','المريض':'patient','أُلغيت الخطة بقرار الإدارة.':'Plan cancelled by administration.','تعذر العثور على ملف الخطة الكامل':'The complete plan record was not found','تعذر حفظ الخطة':'Could not save the plan','تعذر تحديث فهرس الخطط':'Could not update the plan registry','تعذر حذف الخطة':'Could not delete the plan'};
PLAN_TRANSLATIONS['إضافة خطة سريعة']='Add quick plan';
const tr=value=>language==='en'?(PLAN_TRANSLATIONS[value]||value):value;
const formatDate=value=>new Date(value).toLocaleString(language==='en'?'en-GB':'ar-SA-u-ca-gregory-nu-latn');
function updateQuickPlanLink(){const link=document.querySelector('.quick-plan-add');if(!link)return;const selected=$('clinicFilter')?.value,clinic=selected&&selected!=='all'?selected:'clinic-1';link.href=`./quick-plan?${new URLSearchParams({clinic,lang:language})}`}
function translatePage(){document.documentElement.lang=language;document.documentElement.dir=language==='en'?'ltr':'rtl';document.title=tr('مركز الخطط العلاجية | أفضل عناية');const reverse=Object.fromEntries(Object.entries(PLAN_TRANSLATIONS).map(([ar,en])=>[en,ar]));const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement?.closest('#planList,#errorBox'))continue;const raw=node.nodeValue,trim=raw.trim(),ar=reverse[trim]||trim,translated=tr(ar);if(trim&&translated!==trim)node.nodeValue=raw.replace(trim,translated)}document.querySelectorAll('[placeholder],[aria-label],[alt]').forEach(element=>{for(const attr of ['placeholder','aria-label','alt']){const value=element.getAttribute(attr);if(value)element.setAttribute(attr,tr(reverse[value]||value))}});$('languageToggle').textContent=language==='en'?'العربية':'English';$('languageToggle').setAttribute('aria-label',language==='en'?'Switch to Arabic':'التبديل إلى الإنجليزية');document.querySelector('.topbar a.btn').href=`./?view=admin&lang=${language}`;updateQuickPlanLink()}
const LABELS={draft:'قيد إعداد الإدارة',submitted:'جاهزة لمشاركة وتوقيع المريض',patient_accepted:'وافق ووقّع',approved:'خطة معتمدة',approved_signed:'خطة معتمدة وموقعة',rejected:'تحتاج تصحيح',cancelled:'خطة ملغاة'};
const needsAction=status=>['draft','submitted','patient_accepted','rejected'].includes(status);
const canManageStatus=(current,next)=>current===next
  ||(next==='cancelled'&&current!=='cancelled')
  ||(current==='cancelled'&&next==='draft')
  ||(['submitted','patient_accepted','approved','approved_signed'].includes(current)&&next==='rejected');
let records={},aliases={},clinics=[];
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const request=async(url,options={})=>fetch(url,{credentials:'include',...options});
const isZero=value=>/^0+$/.test(String(value??'').trim());
const photoAlert=record=>{if(!record||!['approved','approved_signed'].includes(record.status))return'';const recorded=record.photoConsentRecorded===true||(Number(record.consentTermsVersion||0)>=2&&Number(record.patientAcceptedAt||0)>0);if(!recorded)return`<span class="warning photo-unrecorded">⚠ ${tr('موافقة التصوير غير موثقة')}</span>`;return record.photoConsent===true?'':`<span class="warning photo-declined">⚠ ${tr('المريض لم يوقّع على موافقة التصوير')}</span>`};
const entries=()=>Object.entries(records).map(([canonical,record])=>({canonical,record})).sort((a,b)=>Number(b.record.updatedAt||0)-Number(a.record.updatedAt||0));
const clinicLabel=id=>{const clinic=clinics.find(item=>item.id===id);if(!clinic)return`${tr('العيادة')} ${Math.max(1,Math.min(15,Number(String(id||'clinic-1').split('-')[1])||1))}`;return`${tr(clinic.name||'العيادة')}${clinic.roomNumber?` · ${tr('رقم')} ${clinic.roomNumber}`:''}${clinic.doctorName?` · ${tr('د.')} ${clinic.doctorName}`:''}`};
function syncClinics(){const current=$('clinicFilter').value||'all',ids=[...new Set(entries().map(item=>item.record.clinicId).filter(Boolean))].sort();$('clinicFilter').innerHTML=`<option value="all">${tr('جميع العيادات')}</option>`+ids.map(id=>`<option value="${esc(id)}">${esc(clinicLabel(id))}</option>`).join('');$('clinicFilter').value=ids.includes(current)?current:'all'}
function render(){
  syncClinics();updateQuickPlanLink();const all=entries(),pending=all.filter(({record})=>needsAction(record.status)),zero=all.filter(({canonical,record})=>isZero(record.fileNo)||/^file:0+$/i.test(canonical));
  $('totalCount').textContent=all.length;$('pendingCount').textContent=pending.length;$('approvedCount').textContent=all.filter(({record})=>record.status==='approved_signed').length;$('zeroCount').textContent=zero.length;
  const q=$('searchInput').value.trim().toLowerCase(),clinic=$('clinicFilter').value,status=$('statusFilter').value;
  const visible=all.filter(({record})=>clinic==='all'||record.clinicId===clinic).filter(({record})=>status==='all'||status==='unapproved'&&needsAction(record.status)||record.status===status).filter(({record})=>!q||`${record.fullName||''} ${record.fileNo||''} ${record.mobile||''} ${record.planNo||''}`.toLowerCase().includes(q));
  if(!visible.length){$('planList').innerHTML=`<p class="empty">${tr('لا توجد خطط مطابقة للتصفية.')}</p>`;return}
  $('planList').innerHTML=visible.map(({canonical,record})=>{const planStatus=STATUSES.includes(record.status)?record.status:'draft',pending=needsAction(planStatus),zeroFile=isZero(record.fileNo)||/^file:0+$/i.test(canonical),canOpen=record.sourcePatientId&&/^\d{4}-\d{2}-\d{2}$/.test(record.sourceDate||'');return`<article class="card status-${esc(planStatus)} ${pending?'pending':''} ${zeroFile?'zero':''}" data-key="${esc(canonical)}"><div class="patient"><strong>${esc(record.fullName||tr('مريض بدون اسم'))}</strong><small>${record.planNo?`${tr('خطة')} ${esc(record.planNo)} · `:''}${tr('ملف')} ${esc(record.fileNo||tr('غير مسجل'))}${record.mobile?` · ${esc(record.mobile)}`:''}</small>${zeroFile?`<span class="warning">⚠ ${tr('رقم الملف 0 مشترك — يجب تصحيحه')}</span>`:''}${planStatus==='submitted'?`<span class="warning">${tr('الخطة جاهزة للمشاركة وإرسال رابط توقيع المريض')}</span>`:''}${photoAlert(record)}${planStatus==='cancelled'&&record.cancellationReason?`<span class="cancel-note">${tr('سبب الإلغاء:')} ${esc(record.cancellationReason)}</span>`:''}</div><div class="clinic"><strong>${esc(clinicLabel(record.clinicId))}</strong><small>${record.updatedAt?formatDate(record.updatedAt):'—'}</small></div><label class="status">${tr('حالة الاعتماد')}<select data-status="${esc(canonical)}">${STATUSES.map(value=>`<option value="${value}" ${planStatus===value?'selected':''} ${canManageStatus(planStatus,value)?'':'disabled'}>${esc(tr(LABELS[value]))}</option>`).join('')}</select></label><div class="card-actions icon-actions">${planStatus==='submitted'?`<button type="button" class="share-ready" data-share="${esc(canonical)}" ${canOpen?'':'disabled'}><span aria-hidden="true">↗</span> ${tr('مشاركة الخطة والتوقيع')}</button>`:''}<button type="button" data-open="${esc(canonical)}" ${canOpen?'':'disabled'}><span aria-hidden="true">▤</span> ${tr('فتح وتعديل')}</button><button type="button" class="danger" data-delete="${esc(canonical)}"><span aria-hidden="true">×</span> ${tr('حذف')}</button></div></article>`}).join('');
  const focus=new URLSearchParams(location.search).get('focus');if(focus){const node=[...document.querySelectorAll('[data-key]')].find(item=>item.dataset.key===focus);node?.scrollIntoView({block:'center'});node?.animate?.([{boxShadow:'0 0 0 0 rgba(49,95,133,0)'},{boxShadow:'0 0 0 8px rgba(49,95,133,.2)'},{boxShadow:'0 8px 23px rgba(38,77,103,.07)'}],{duration:1400})}
}
async function load(){try{$('errorBox').hidden=true;const [planResponse,clinicResponse]=await Promise.all([request(`${API}?clinic=clinic-1&includeHistory=1&_=${Date.now()}`),request('/api/clinics')]),data=await planResponse.json().catch(()=>({})),clinicData=await clinicResponse.json().catch(()=>({}));if(planResponse.status===401)throw new Error(tr('يلزم تسجيل الدخول من لوحة الإدارة أولًا.'));if(!planResponse.ok)throw new Error(tr(data.error||'تعذر تحميل الخطط'));records=data.records||{};aliases=data.aliases||{};clinics=Array.isArray(clinicData.clinics)?clinicData.clinics:[];render()}catch(error){$('errorBox').textContent=error.message;$('errorBox').hidden=false;$('planList').innerHTML=`<p class="empty"><a class="btn" href="./?view=admin&lang=${language}">${tr('فتح صفحة الدخول')}</a></p>`}}
function openPlan(canonical,{share=false}={}){const record=records[canonical];if(!record)return;localStorage.setItem(`bestcare_treatment_source_${record.sourcePatientId}`,JSON.stringify({__bestcareSource:1,expiresAt:Date.now()+12*60*60*1000,source:{id:record.sourcePatientId,name:record.fullName||'',file:record.fileNo||'',phone:record.mobile||'',nationalId:record.nationalId||'',date:record.sourceDate,view:'admin',returnUrl:location.href}}));const params=new URLSearchParams({patientId:record.sourcePatientId,date:record.sourceDate,planNo:record.planNo||'',clinic:record.clinicId||'clinic-1',view:'admin',lang:language});if(share&&record.status==='submitted')params.set('action','share');location.href=`./treatment-plan.html?${params}`}
function updateMeta(plan,status,cancellationReason=''){const now=Date.now();plan.meta=plan.meta&&typeof plan.meta==='object'?plan.meta:{};plan.meta.status=status;if(status!=='cancelled')Object.assign(plan.meta,{cancelledAt:0,cancelledBy:'',cancellationReason:''});if(status==='draft')Object.assign(plan.meta,{doctorApprovedAt:0,doctorApprovedBy:'',administrationPreparedAt:0,administrationPreparedBy:'',submittedAt:0,patientAcceptedAt:0,patientAcceptedBy:'',approvedAt:0,approvedBy:'',rejectedAt:0,rejectedBy:'',rejectionReason:''});else if(status==='submitted')Object.assign(plan.meta,{doctorApprovedAt:0,doctorApprovedBy:'',administrationPreparedAt:now,administrationPreparedBy:'الإدارة',submittedAt:now,patientAcceptedAt:0,patientAcceptedBy:'',approvedAt:0,approvedBy:'',rejectedAt:0,rejectedBy:'',rejectionReason:''});else if(status==='patient_accepted')Object.assign(plan.meta,{patientAcceptedAt:now,patientAcceptedBy:'الإدارة',approvedAt:0,approvedBy:'',rejectedAt:0,rejectedBy:'',rejectionReason:''});else if(['approved','approved_signed'].includes(status))Object.assign(plan.meta,{approvedAt:now,approvedBy:'الإدارة',rejectedAt:0,rejectedBy:'',rejectionReason:'',revision:Math.max(1,Number(plan.meta.revision||1)+1)});else if(status==='rejected')Object.assign(plan.meta,{rejectedAt:now,rejectedBy:'الإدارة',rejectionReason:'تحتاج الخطة إلى مراجعة الإجراءات أو الأسعار.',patientAcceptedAt:0,patientAcceptedBy:'',approvedAt:0,approvedBy:''});else if(status==='cancelled')Object.assign(plan.meta,{cancelledAt:now,cancelledBy:'الإدارة',cancellationReason:String(cancellationReason||'أُلغيت الخطة بقرار الإدارة.').trim().slice(0,500)})}
async function changeStatus(canonical,status,select){
  const record=records[canonical],previous=record?.status;
  if(!record||status===previous)return;
  if(!canManageStatus(previous,status)){select.value=previous;alert(tr('لا يمكن اعتماد الخطة يدويًا. افتح الخطة وشارك رابط التوقيع؛ يتم الاعتماد النهائي تلقائيًا بعد توقيع المريض.'));return}
  let cancellationReason='';
  if(status==='cancelled'){
    cancellationReason=prompt(language==='en'?`Reason for cancelling ${record.fullName||'patient'}'s plan:`:`سبب إلغاء خطة ${record.fullName||'المريض'}:`,tr('أُلغيت الخطة بقرار الإدارة.'));
    if(cancellationReason===null){select.value=previous;return}
  }else if(!confirm(language==='en'?`Change ${record.fullName||'patient'}'s plan status to “${tr(LABELS[status])}”?`:`تغيير حالة خطة ${record.fullName||'المريض'} إلى «${LABELS[status]}»؟`)){select.value=previous;return}
  select.disabled=true;
  try{
    const params=new URLSearchParams({patientId:record.sourcePatientId,date:record.sourceDate,planNo:record.planNo||'',clinic:record.clinicId||'clinic-1'}),loaded=await request(`/api/treatment-plan?${params}`),data=await loaded.json();
    if(!loaded.ok||!data.exists||!data.plan)throw new Error(tr('تعذر العثور على ملف الخطة الكامل'));
    updateMeta(data.plan,status,cancellationReason);
    const saved=await request(`/api/treatment-plan?${params}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({plan:data.plan})});
    if(!saved.ok)throw new Error(tr('تعذر حفظ الخطة'));
    const indexed=await request(`${API}?clinic=${encodeURIComponent(record.clinicId||'clinic-1')}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({canonical,patient:{fullName:record.fullName,fileNo:record.fileNo,mobile:record.mobile,nationalId:record.nationalId},status,planNo:record.planNo,parentPlanNo:record.parentPlanNo||'',relation:record.relation||'standalone',preparedByRole:data.plan.meta?.administrationPreparedAt?'administration':data.plan.meta?.doctorApprovedAt?'doctor':'',administrationPreparedAt:data.plan.meta?.administrationPreparedAt||0,administrationPreparedBy:data.plan.meta?.administrationPreparedBy||'',sourcePatientId:record.sourcePatientId,sourceDate:record.sourceDate,patientAcceptedAt:data.plan.meta?.patientAcceptedAt||0,photoConsent:data.plan.consent?.photoConsent===true,photoConsentRecorded:data.plan.consent?.photoConsentRecorded===true||(Number(data.plan.consent?.termsVersion||0)>=2&&Number(data.plan.meta?.patientAcceptedAt||0)>0),consentTermsVersion:Number(data.plan.consent?.termsVersion||0),cancelledAt:data.plan.meta?.cancelledAt||0,cancelledBy:data.plan.meta?.cancelledBy||'',cancellationReason:data.plan.meta?.cancellationReason||''})});
    if(!indexed.ok)throw new Error(tr('تعذر تحديث فهرس الخطط'));
    await load();
  }catch(error){select.value=previous;alert(error.message)}finally{select.disabled=false}
}
async function removePlan(canonical){const record=records[canonical];if(!record||!confirm(language==='en'?`Permanently delete ${record.fullName||'patient'}'s plan?`:`حذف خطة ${record.fullName||'المريض'} نهائيًا؟`))return;try{const response=await request(`${API}?clinic=${encodeURIComponent(record.clinicId||'clinic-1')}`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({canonical})}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(tr(data.error||'تعذر حذف الخطة'));await load()}catch(error){alert(error.message)}}
$('refreshBtn').addEventListener('click',load);$('searchInput').addEventListener('input',render);$('clinicFilter').addEventListener('change',render);$('statusFilter').addEventListener('change',render);$('clearFilters').addEventListener('click',()=>{$('searchInput').value='';$('clinicFilter').value='all';$('statusFilter').value='all';render()});$('planList').addEventListener('click',event=>{const share=event.target.closest('[data-share]')?.dataset.share,open=event.target.closest('[data-open]')?.dataset.open,remove=event.target.closest('[data-delete]')?.dataset.delete;if(share)openPlan(share,{share:true});else if(open)openPlan(open);if(remove)removePlan(remove)});$('planList').addEventListener('change',event=>{const key=event.target.dataset.status;if(key)changeStatus(key,event.target.value,event.target)});$('languageToggle').addEventListener('click',()=>{language=language==='en'?'ar':'en';localStorage.setItem('bestcare_lang',language);const url=new URL(location.href);url.searchParams.set('lang',language);history.replaceState(null,'',url);translatePage();render()});translatePage();load();
})();
